name: Snake Animation

on:
  schedule:
    - cron: "0 */24 * * *" 
  
  workflow_dispatch:

  push:
    branches:
    - edge
    
jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      - uses: actions/checkout@v3
      - run: mkdir -vp dist
      - name: generate github-contribution-grid-snake.svg
        uses: Platane/snk/svg-only@v2
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
      - uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          
